install.packages("ggplot2")
install.packages("shiny")
install.packages("dplyr")
install.packages("plotly")
install.packages("shinydashboard")
install.packages("shinyWidgets")
install.packages("rgeos", type="source")
install.packages("rworldmap")
install.packages("RPostgreSQL")
install.packages("RPostgres")
install.packages("rworldxtra")
