install.packages("ggplot2")
install.packages("shiny")
install.packages("dplyr")
install.packages("plotly")
install.packages("shinydashboard")
install.packages("rgeos")
install.packages('maps', repos='http://cran.us.r-project.org')
install.packages("rworldmap")
install.packages("shinyWidgets")
install.packages("hash")
install.packages("https://cran.r-project.org/src/contrib/Archive/data.table/data.table_1.14.2.tar.gz", repo=NULL, type="source")
